name: synapse_frontend
description: "Synapse: AI-Powered Neuro-adaptive Learning Platform."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  google_fonts: ^6.1.0
  flutter_markdown: ^0.6.14
  youtube_player_flutter: ^9.0.0
  flutter_tts: ^3.8.3
  provider: ^6.0.0
  file_picker: ^6.1.1
  url_launcher: ^6.2.0
  flutter_math_fork: ^0.7.2
  uuid: ^4.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

